.TH shell-language-server 1 shell-language-server-0.1.0

.SH NAME
shell-language-server

.SH SYNOPSIS
shell-language-server [option]...

.SH DESCRIPTION
A language server for shell scripts.

.SH OPTIONS

.TP
\fB--help\fP, \fB-h\fP
Display help information.

.TP
\fB--version\fP, \fB-v\fP
Display version information.

.TP
.B --settings-json=\fIARG\fP
Provide server initialization settings.

.TP
.B --debug
Log every LSP request and response to standard error.

.SH EXIT STATUS

.TP
0
Success: everything went well.

.TP
1
Unexpected exit: an exit notification was received before the corresponding shutdown notification.

.TP
2
Transport error: failed to read or write LSP message.

.TP
3
Invalid command line: could not parse one or more arguments.

.SH AUTHOR
Written by aattoa <aattoa@proton.me>
